# 無効にするルール
disabled_rules:
- function_body_length
- line_length
- trailing_whitespace

# チェック対象ファイル
included:
- {プロジェクト直下のファイル名}

# Class, Struct, Enumの行数制限
type_body_length:
- 400
- 600

# 1ファイルの行数制限
file_length:
- 600
- 1000
